<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教师管理",
			            "menuJump":"列表",
			            "tableName":"jiaoshi"
			        }
			    ],
			    "menu":"教师管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"实验室管理",
			            "menuJump":"列表",
			            "tableName":"shiyanshi"
			        }
			    ],
			    "menu":"实验室管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"实验室预约管理",
			            "menuJump":"列表",
			            "tableName":"yuyue"
			        }
			    ],
			    "menu":"实验室预约管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"班级管理",
                        "menuJump":"列表",
                        "tableName":"banji"
                    }
                ],
                "menu":"班级管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"签到管理",
                        "menuJump":"列表",
                        "tableName":"qiandao"
                    }
                ],
                "menu":"签到管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			
			    ],
			    "menu":"公告类型管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    },
	{
        "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "预约"			            ],
			            "menu":"实验室管理",
			            "menuJump":"列表",
			            "tableName":"shiyanshi"
			        }
			    ],
			    "menu":"实验室管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"课程签到管理",
			            "menuJump":"列表",
			            "tableName":"yuyue"
			        }
			    ],
			    "menu":"课程签到管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"班级管理",
                        "menuJump":"列表",
                        "tableName":"banji"
                    }
                ],
                "menu":"班级管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"教师",
        "tableName":"jiaoshi"
    },
	{
	    "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"实验室管理",
			            "menuJump":"列表",
			            "tableName":"shiyanshi"
			        }
			    ],
			    "menu":"实验室管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "签到",
			                "签退"
			            ],
			            "menu":"实验室预约管理",
			            "menuJump":"列表",
			            "tableName":"yuyue"
			        }
			    ],
			    "menu":"实验室预约管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"班级管理",
	                    "menuJump":"列表",
	                    "tableName":"banji"
	                }
	            ],
	            "menu":"班级管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"签到管理",
	                    "menuJump":"列表",
	                    "tableName":"qiandao"
	                }
	            ],
	            "menu":"签到管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
	    ],
	    "frontMenu":[
	    ],
	    "roleName":"学生",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
